CSCFAIRMETA-676-cannot-delete-next-draft
CSCfi/metax-api pull request #636
Opened 2020-09-23 11:24 UTC by katrite

- Move handling of next_draft directly under v1
- Change models/common def delete to delete directly
- models/common def remove handles 'deleting' of datasets

2020-09-28 19:08 UTC, katrite commented on src/metax_api/models/xml_metadata.py
> +        super().remove()
It was pointing on this method in models/common: 

    def delete(self):
        """
        Mark record as removed, never delete from db.
        """
        self._set_removed()
        super().save(update_fields=['removed', 'date_removed', 'date_modified'])
        self._update_tracked_field_values()



......In this code change I renamed this function to be 'def remove', and redirected function calls to this 'remove' method to keep 'old functionality' intact.

2020-09-29 11:57 UTC, genie9 approved these changes

2020-10-21 08:25 UTC, genie9 requested changes

2020-10-21 08:25 UTC, genie9 commented on src/metax_api/tests/api/rest/v2/views/datasets/drafts.py
> +        original_found = CR.objects_unfiltered.filter(pk=draft_cr['id']).exists()
pk=draft_cr['id'] should be probably pk=draft_cr['id']

2020-10-21 14:17 UTC, katrite commented
Actually tests for this can't be done before bugfix https://jira.eduuni.fi/browse/CSCFAIRMETA-771

2020-10-22 11:00 UTC, genie9 submitted a review, later dismissed

2020-10-22 13:32 UTC, merged